name: DevInfra

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: angular/dev-infra/github-actions/commit-message-based-labels@a9c48602d4f54850beabdf7933e05a9ce89e9dd5
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
