name: Feature request triage bot

on:
  schedule:
    # Run at 15:00 every day
    - cron: '0 15 * * *'

jobs:
  feature_triage:
    if: github.repository == 'angular/components'
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/feature-request@a9c48602d4f54850beabdf7933e05a9ce89e9dd5
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
